networks:
  frontend:
    external: true
  backend:

services:
  nginx:
    build: ./docker/dev/nginx
    container_name: nginx_travel
    restart: unless-stopped
    volumes:
      - .:/var/www/travel
    ports:
      - "127.0.0.1:8081:80"
    networks:
      backend:
        aliases:
          - travel.test


  php:
    build: ./docker/dev/php
    container_name: php_travel
    networks:
      - backend
    environment:
      - COMPOSER_MEMORY_LIMIT=2G
      - XDEBUG_SESSION="PHPSTORM"
    volumes:
      - .:/var/www/travel
      - ./storage/logs:/var/log/php
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  postgres:
    image: postgres:latest
    container_name: travel_postgres
    restart: unless-stopped
    ports:
      - '5441:5432'
    environment:
      POSTGRES_DB: travel
      POSTGRES_USER: travel
      POSTGRES_PASSWORD: travel
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata_travel:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: bitnami/redis:latest
    container_name: travel_redis
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - backend

  supervisor:
    build: ./docker/dev/supervisor
    container_name: supervisor_travel
    networks:
      - backend
    volumes:
      - .:/var/www/travel
      - ./storage/logs:/var/log/php

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      # AMQP protocol port
      - '5679:5672'
      # HTTP management UI
      - '15679:15672'
    volumes:
      - ./docker/rabbitmq/data/:/var/lib/rabbitmq/
    networks:
      - backend

volumes:
  pgdata_travel:
  redis_data:
