networks:
  frontend:
    external: true
  backend:

services:
  nginx:
    build: ./docker/nginx
    container_name: nginx_travel
    volumes:
      - .:/var/www/travel
    environment:
      - VIRTUAL_HOST=travel.test
    ports:
      - "80:80"
    networks:
      frontend:
      backend:
        aliases:
          - travel.test

  php:
    build: ./docker/php
    container_name: php_travel
    networks:
      - backend
    environment:
      - COMPOSER_MEMORY_LIMIT=2G
      - XDEBUG_SESSION="PHPSTORM"
    volumes:
      - .:/var/www/travel
      - ./storage/logs:/var/log/php
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  postgres:
    image: postgres:latest
    networks:
      frontend:
      backend:
    ports:
      - '5441:5432'
    environment:
      POSTGRES_DB: travel
      POSTGRES_USER: travel
      POSTGRES_PASSWORD: travel
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./docker/postgres/travel:/var/lib/postgresql/data

  redis:
    image: bitnami/redis:latest
    networks:
      - backend
      - frontend
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  supervisor:
    build: ./docker/supervisor
    container_name: supervisor_travel
    networks:
      - backend
    volumes:
      - .:/var/www/travel
      - ./storage/logs:/var/log/php

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      # AMQP protocol port
      - '5679:5672'
      # HTTP management UI
      - '15679:15672'
    volumes:
      - ./docker/rabbitmq/data/:/var/lib/rabbitmq/
    networks:
      - backend

  #elasticsearch:
  #  image: elasticsearch:9.0.2
  #  container_name: elasticsearch_travel
  #  environment:
  #    - xpack.security.enabled=true
  #    - xpack.security.authc.api_key.enabled=true
  #    - discovery.type=single-node
  #    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #    - ELASTIC_USERNAME=elastic
  #    - ELASTIC_PASSWORD=root
  #  volumes:
  #    - ./docker/elasticsearch/data:/usr/share/elasticsearch/data
  #  networks:
  #    - frontend
  #    - backend
  #  ports:
  #    - "9200:9200"
  #    - "9300:9300"

  #kibana:
  #  image: kibana:9.0.2
  #  environment:
  #    - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #    - ELASTICSEARCH_USERNAME=elastic
  #    - ELASTICSEARCH_PASSWORD=root
  #  ports:
  #    - "5601:5601"
  #  networks:
  #    frontend:
  #    backend:
  #  depends_on:
  #    - elasticsearch
