networks:
  backend:

services:
  nginx:
    build: ./docker/nginx
    container_name: nginx_outvento
    volumes:
      - .:/var/www/outvento
    environment:
      - VIRTUAL_HOST=outvento.test
    ports:
      - "80:80"
    networks:
      backend:
        aliases:
          - outvento.test

  php:
    build: ./docker/php
    container_name: php_outvento
    mem_limit: 1g
    cpus: "2.0"
    networks:
      - backend
    environment:
      - COMPOSER_MEMORY_LIMIT=2G
      - XDEBUG_SESSION="PHPSTORM"
    volumes:
      - .:/var/www/outvento
      - ./storage/logs:/var/log/php
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  postgres:
    image: postgis/postgis:16-3.4
    platform: linux/amd64
    networks:
      backend:
    mem_limit: 512m
    cpus: "1.0"
    ports:
      - '5441:5432'
    environment:
      POSTGRES_DB: outvento
      POSTGRES_USER: outvento
      POSTGRES_PASSWORD: outvento
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./docker/postgres/outvento:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d

  redis:
    image: bitnami/redis:latest
    networks:
      - backend
    mem_limit: 256m
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  supervisor:
    build: ./docker/supervisor
    container_name: supervisor_outvento
    networks:
      - backend
    volumes:
      - .:/var/www/outvento
      - ./storage/logs:/var/log/php

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - '5679:5672'
      - '15679:15672'
    volumes:
      - ./docker/rabbitmq/data/:/var/lib/rabbitmq/
    networks:
      - backend

