insert into public.countries (id, name_ru, name_en, name_pl, iso3166alpha2, iso3166alpha3, iso3166numeric, continent)
values  (3, 'Афганистан', 'Afghanistan', 'Afganistan', 'AF ', 'AFG ', '4  ', 2),
        (5, 'Ангилья', 'Angilla', 'Angilla', 'AI ', 'AIA ', '660', 4),
        (6, 'Албания', 'Albania', 'Albania', 'AL ', 'ALB ', '8  ', 3),
        (7, 'Армения', 'Armenia', 'Armenia', 'AM ', 'ARM ', '51 ', 2),
        (9, 'Ангола', 'Angola', 'Angola', 'AO ', 'AGO ', '24 ', 1),
        (10, 'Антарктика', 'Antarctic', 'Antarktyda', 'AQ ', 'ATA ', '10 ', 7),
        (11, 'Аргентина', 'Argentina', 'Argentyna', 'AR ', 'ARG ', '32 ', 6),
        (12, 'Американское Самоа', 'American Samoa', 'Samoa American', 'AS ', 'ASM ', '16 ', 5),
        (13, 'Австрия', 'Austria', 'Austria', 'AT ', 'AUT ', '40 ', 3),
        (15, 'Аруба', 'Aruba', 'Aruba', 'AW ', 'ABW ', '533', 4),
        (16, 'Азербайджан', 'Azerbaijan', 'Azerbejdżan', 'AZ ', 'AZE ', '31 ', 2),
        (18, 'Барбадос', 'Barbados', 'Barbados', 'BB ', 'BRB ', '52 ', 4),
        (19, 'Бангладеш', 'Bangladesh', 'Bangladesz', 'BD ', 'BGD ', '50 ', 2),
        (20, 'Бельгия', 'Belgium', 'Belgia', 'BE ', 'BEL ', '56 ', 3),
        (22, 'Болгария', 'Bulgaria', 'Bułgaria', 'BG ', 'BGR ', '100', 3),
        (23, 'Бахрейн', 'Bahrain', 'Bahrajn', 'BH ', 'BHR ', '48 ', 2),
        (24, 'Бурунди', 'Burundi', 'Burundi', 'BI ', 'BDI ', '108', 1),
        (25, 'Бенин', 'Benin', 'Benin', 'BJ ', 'BEN ', '204', 1),
        (27, 'Бермуды', 'Bermuda', 'Bermudy', 'BM ', 'BMU ', '60 ', 4),
        (28, 'Бруней', 'Brunei', 'Brunei', 'BN ', 'BRN ', '96 ', 2),
        (29, 'Боливия', 'Bolivia', 'Boliwia', 'BO ', 'BOL ', '68 ', 6),
        (31, 'Багамы', 'Bagam', 'Bagam', 'BS ', 'BHS ', '44 ', 4),
        (32, 'Бутан', 'Butane', 'Butan', 'BT ', 'BTN ', '64 ', 2),
        (33, 'Остров Буве', 'Island of Buva', 'Wyspa Buva', 'BV ', 'BVT ', '74 ', 7),
        (35, 'Беларусь', 'Belarus', 'Białoruś', 'BY ', 'BLR ', '112', 3),
        (36, 'Белиз', 'Belize', 'Belize', 'BZ ', 'BLZ ', '84 ', 4),
        (37, 'Канада', 'Canada', 'Kanada', 'CA ', 'CAN ', '124', 4),
        (39, 'ДР Конго', 'DR Congo', 'Dr Kongo', 'CD ', 'COD ', '180', 1),
        (41, 'Конго', 'Congo', 'Kongo', 'CG ', 'COG ', '178', 1),
        (42, 'Швейцария', 'Switzerland', 'Szwajcaria', 'CH ', 'CHE ', '756', 3),
        (43, 'Кот-д''Ивуар', 'Cat-d''Ivoire', 'Cat-d''ivoire', 'CI ', 'CIV ', '384', 1),
        (44, 'Китай', 'China', 'Chiny', 'CN ', 'CHN ', '156', 2),
        (45, 'Колумбия', 'Colombia', 'Kolumbia', 'CO ', 'COL ', '170', 6),
        (46, 'Коста-Рика', 'Costa Rica', 'Kostaryka', 'CR ', 'CRI ', '188', 4),
        (48, 'Куба', 'Cuba', 'Kuba', 'CU ', 'CUB ', '192', 4),
        (49, 'Кабо-Верде', 'Cape Verde', 'Cape Verde', 'CV ', 'CPV ', '132', 1),
        (50, 'Кюрасао', 'Curasao', 'Curasao', 'CW ', 'CUW ', '531', 4),
        (52, 'Кипр', 'Cyprus', 'Cypr', 'CY ', 'CYP ', '196', 3),
        (53, 'Чехия', 'Czech Republic', 'Czechy', 'CZ ', 'CZE ', '203', 3),
        (54, 'Германия', 'Germany', 'Niemcy', 'DE ', 'DEU ', '276', 3),
        (56, 'Дания', 'Denmark', 'Dania', 'DK ', 'DNK ', '208', 3),
        (57, 'Доминика', 'Dominica', 'Dominika', 'DM ', 'DMA ', '212', 4),
        (59, 'Алжир', 'Algeria', 'Algieria', 'DZ ', 'DZA ', '12 ', 1),
        (60, 'Экадор', 'Ecador', 'Ecador', 'EC ', 'ECU ', '218', 6),
        (61, 'Эстония', 'Estonia', 'Estonia', 'EE ', 'EST ', '233', 3),
        (62, 'Египет', 'Egypt', 'Egipt', 'EG ', 'EGY ', '818', 1),
        (64, 'Эритрея', 'Eritrea', 'Erytrea', 'ER ', 'ERI ', '232', 1),
        (65, 'Испания', 'Spain', 'Hiszpania', 'ES ', 'ESP ', '724', 3),
        (66, 'Эфиопия', 'Ethiopia', 'Etiopia', 'ET ', 'ETH ', '231', 1),
        (67, 'Финляндия', 'Finland', 'Finlandia', 'FI ', 'FIN ', '246', 3),
        (68, 'Фиджи', 'Fiji', 'Fidżi', 'FJ ', 'FJI ', '242', 5),
        (71, 'Фарерские о-ва', 'Faroe island', 'Wyspa Faroe', 'FO ', 'FRO ', '234', 3),
        (72, 'Франция', 'France', 'Francja', 'FR ', 'FRA ', '250', 3),
        (73, 'Габон', 'Gabon', 'Gabon', 'GA ', 'GAB ', '266', 1),
        (74, 'Великобритания', 'United Kingdom', 'Zjednoczone Królestwo', 'GB ', 'GBR ', '826', 3),
        (75, 'Гренада', 'Grenada', 'Grenada', 'GD ', 'GRD ', '308', 4),
        (76, 'Грузия', 'Georgia', 'Gruzja', 'GE ', 'GEO ', '268', 2),
        (78, 'Гернси', 'Gernssey', 'Gernssey', 'GG ', 'GGY ', '831', 3),
        (79, 'Гана', 'Ghana', 'Ghana', 'GH ', 'GHA ', '288', 1),
        (80, 'Гибралтар', 'Gibraltar', 'Gibraltar', 'GI ', 'GIB ', '292', 3),
        (82, 'Гамбия', 'Gambia', 'Gambia', 'GM ', 'GMB ', '270', 1),
        (83, 'Гвинея', 'Guinea', 'Gwinea', 'GN ', 'GIN ', '324', 1),
        (84, 'Гваделупа', 'Guadelup', 'Guadelup', 'GP ', 'GLP ', '312', 4),
        (86, 'Греция', 'Greece', 'Grecja', 'GR ', 'GRC ', '300', 3),
        (88, 'Гватемала', 'Guatemala', 'Gwatemala', 'GT ', 'GTM ', '320', 4),
        (89, 'Гуам', 'Guam', 'Guam', 'GU ', 'GUM ', '316', 5),
        (90, 'Гвинея-Бисау', 'Guinea-Bisau', 'Gwinea-Bisau', 'GW ', 'GNB ', '624', 1),
        (91, 'Гайана', 'Guyana', 'Gujana', 'GY ', 'GUY ', '328', 6),
        (92, 'Гонконг', 'Hong Kong', 'Hongkong', 'HK ', 'HKG ', '344', 2),
        (94, 'Гондурас', 'Honduras', 'Honduras', 'HN ', 'HND ', '340', 4),
        (95, 'Хорватия', 'Croatia', 'Chorwacja', 'HR ', 'HRV ', '191', 3),
        (96, 'Гаити', 'Haiti', 'Haiti', 'HT ', 'HTI ', '332', 4),
        (97, 'Венгрия', 'Hungary', 'Węgry', 'HU ', 'HUN ', '348', 3),
        (98, 'Индонезия', 'Indonesia', 'Indonezja', 'ID ', 'IDN ', '360', 2),
        (100, 'Израиль', 'Israel', 'Izrael', 'IL ', 'ISR ', '376', 2),
        (102, 'Индия', 'India', 'Indie', 'IN ', 'IND ', '356', 2),
        (104, 'Ирак', 'Iraq', 'Irak', 'IQ ', 'IRQ ', '368', 2),
        (105, 'Иран', 'Iran', 'Iran', 'IR ', 'IRN ', '364', 2),
        (106, 'Исландия', 'Iceland', 'Islandia', 'IS ', 'ISL ', '352', 3),
        (107, 'Италия', 'Italy', 'Włochy', 'IT ', 'ITA ', '380', 3),
        (108, 'Джерси', 'Jersey', 'Golf', 'JE ', 'JEY ', '832', 3),
        (109, 'Ямайка', 'Jamaica', 'Jamajka', 'JM ', 'JAM ', '388', 4),
        (110, 'Иордания', 'Jordan', 'Jordania', 'JO ', 'JOR ', '400', 2),
        (112, 'Кения', 'Kenya', 'Kenia', 'KE ', 'KEN ', '404', 1),
        (113, 'Киргизия', 'Kyrgyzstan', 'Kirgistan', 'KG ', 'KGZ ', '417', 2),
        (115, 'Кирибати', 'Kiribati', 'Kiribati', 'KI ', 'KIR ', '296', 5),
        (116, 'Коморы', 'Comory', 'COMORY', 'KM ', 'COM ', '174', 1),
        (119, 'Южная Корея', 'South Korea', 'Korea Południowa', 'KR ', 'KOR ', '410', 2),
        (120, 'Кувейт', 'Kuwait', 'Kuwejt', 'KW ', 'KWT ', '414', 2),
        (121, 'Острова Кайман', 'Islands Kaiman', 'Wyspy Kaiman', 'KY ', 'CYM ', '136', 4),
        (122, 'Казахстан', 'Kazakhstan', 'Kazachstan', 'KZ ', 'KAZ ', '398', 2),
        (123, 'Лаос', 'Laos', 'Laos', 'LA ', 'LAO ', '418', 2),
        (124, 'Ливан', 'Lebanon', 'Liban', 'LB ', 'LBN ', '422', 2),
        (125, 'Сент-Люсия', 'Saint-Lusia', 'Saint-Lusia', 'LC ', 'LCA ', '662', 4),
        (127, 'Шри-Ланка', 'Sri Lanka', 'Sri Lanka', 'LK ', 'LKA ', '144', 2),
        (128, 'Либерия', 'Liberia', 'Liberia', 'LR ', 'LBR ', '430', 1),
        (129, 'Лесото', 'Lesotho', 'Lesotho', 'LS ', 'LSO ', '426', 1),
        (130, 'Литва', 'Lithuania', 'Litwa', 'LT ', 'LTU ', '440', 3),
        (132, 'Латвия', 'Latvia', 'Łotwa', 'LV ', 'LVA ', '428', 3),
        (133, 'Ливия', 'Libya', 'Libia', 'LY ', 'LBY ', '434', 1),
        (134, 'Марокко', 'Morocco', 'Maroko', 'MA ', 'MAR ', '504', 1),
        (136, 'Молдавия', 'Moldova', 'Moldova', 'MD ', 'MDA ', '498', 3),
        (137, 'Черногория', 'Montenegro', 'Czarnogóra', 'ME ', 'MNE ', '499', 3),
        (139, 'Мадагаскар', 'Madagascar', 'Madagaskar', 'MG ', 'MDG ', '450', 1),
        (140, 'Маршалловы о-ва', 'Marshallovs', 'Marshallovowie', 'MH ', 'MHL ', '584', 5),
        (142, 'Мали', 'Mali', 'Mali', 'ML ', 'MLI ', '466', 1),
        (143, 'Мьянма', 'Myanmar', 'Myanmar', 'MM ', 'MMR ', '104', 2),
        (144, 'Монголия', 'Mongolia', 'Mongolia', 'MN ', 'MNG ', '496', 2),
        (145, 'Макао', 'Macau', 'Makau', 'MO ', 'MAC ', '446', 2),
        (147, 'Мартиника', 'Martinique', 'Martinique', 'MQ ', 'MTQ ', '474', 4),
        (148, 'Мавритания', 'Mauritania', 'Mauritania', 'MR ', 'MRT ', '478', 1),
        (150, 'Мальта', 'Malta', 'Malta', 'MT ', 'MLT ', '470', 3),
        (151, 'Маврикий о.', 'Mauritius about.', 'Mauritius.', 'MU ', 'MUS ', '480', 1),
        (152, 'Мальдивы', 'Maldives', 'Malediwy', 'MV ', 'MDV ', '462', 2),
        (154, 'Мексика', 'Mexico', 'Meksyk', 'MX ', 'MEX ', '484', 4),
        (155, 'Малайзия', 'Malaysia', 'Malezja', 'MY ', 'MYS ', '458', 2),
        (157, 'Намибия', 'Namibia', 'Namibia', 'NA ', 'NAM ', '516', 1),
        (158, 'Новая Каледония', 'New Caledonia', 'Nowa Kaledonia', 'NC ', 'NCL ', '540', 5),
        (159, 'Нигер', 'Niger', 'Niger', 'NE ', 'NER ', '562', 1),
        (161, 'Нигерия', 'Nigeria', 'Nigeria', 'NG ', 'NGA ', '566', 1),
        (162, 'Никарагуа', 'Nicaragua', 'Nikaragua', 'NI ', 'NIC ', '558', 4),
        (164, 'Норвегия', 'Norway', 'Norwegia', 'NO ', 'NOR ', '578', 3),
        (165, 'Непал', 'Nepal', 'Nepal', 'NP ', 'NPL ', '524', 2),
        (166, 'Науру', 'Nauru', 'Nauru', 'NR ', 'NRU ', '520', 5),
        (167, 'Ниуэ', 'Niue', 'Niue', 'NU ', 'NIU ', '570', 5),
        (169, 'Оман', 'Oman', 'Oman', 'OM ', 'OMN ', '512', 2),
        (170, 'Панама', 'Panama', 'Panama', 'PA ', 'PAN ', '591', 4),
        (171, 'Перу', 'Peru', 'Peru', 'PE ', 'PER ', '604', 6),
        (173, 'Папуа-Новая Гвинея', 'Papua-New Guinea', 'Papua-New Gwinea', 'PG ', 'PNG ', '598', 5),
        (174, 'Филиппины', 'Philippines', 'Filipiny', 'PH ', 'PHL ', '608', 2),
        (175, 'Пакистан', 'Pakistan', 'Pakistan', 'PK ', 'PAK ', '586', 2),
        (178, 'о-ва Питкэрн', 'Front Pitkern', 'Front Pitkern', 'PN ', 'PCN ', '612', 5),
        (179, 'Пуэрто-Рико', 'Puerto Rico', 'Puerto Rico', 'PR ', 'PRI ', '630', 4),
        (180, 'Палестина', 'Palestine', 'Palestyna', 'PS ', 'PSE ', '275', 2),
        (181, 'Португалия', 'Portugal', 'Portugalia', 'PT ', 'PRT ', '620', 3),
        (182, 'Палау', 'Palau', 'Palau', 'PW ', 'PLW ', '585', 5),
        (184, 'Катар', 'Qatar', 'Katar', 'QA ', 'QAT ', '634', 2),
        (185, 'Реюньон', 'Reunion', 'Zjazd', 'RE ', 'REU ', '638', 1),
        (186, 'Румыния', 'Romania', 'Rumunia', 'RO ', 'ROU ', '642', 3),
        (187, 'Сербия', 'Serbia', 'Serbia', 'RS ', 'SRB ', '688', 3),
        (189, 'Руанда', 'Rwanda', 'Rwanda', 'RW ', 'RWA ', '646', 1),
        (191, 'Соломоновы о-ва', 'Solomonov', 'Salomonov', 'SB ', 'SLB ', '90 ', 5),
        (192, 'Сейшелы', 'Seychelles', 'Seszele', 'SC ', 'SYC ', '690', 1),
        (193, 'Судан', 'Sudan', 'Sudan', 'SD ', 'SDN ', '729', 1),
        (194, 'Швеция', 'Sweden', 'Szwecja', 'SE ', 'SWE ', '752', 3),
        (196, 'Св. Елены, о-в', 'Sv. Elena, is it', 'SV', 'SH ', 'SHN ', '654', 1),
        (197, 'Словения', 'Slovenia', 'Słowenia', 'SI ', 'SVN ', '705', 3),
        (1, 'Андорра', 'Andorra', 'Andorra', 'AD ', 'AND ', '20 ', 3),
        (2, 'Объединенные Арабские Эмираты', 'United Arab Emirates', 'Emiraty Arabskie', 'AE ', 'ARE ', '784', 2),
        (4, 'Антигуа и Барбуда', 'Antigua and Barbuda', 'Antigua i Barbuda', 'AG ', 'ATG ', '28 ', 4),
        (8, 'Нидерландские Антильские острова', 'Netherlands Antille Islands', 'Wyspy Antille Holands', 'AN ', 'ANT ', '530', 4),
        (14, 'Австралия', 'Australia', 'Australia', 'AU ', 'AUS ', '36 ', 5),
        (17, 'Босния и Герцеговина', 'Bosnia and Herzegovina', 'Bośnia i Hercegowina', 'BA ', 'BIH ', '70 ', 3),
        (21, 'Буркина-Фасо', 'Burkina-Faso', 'Burkina-faso', 'BF ', 'BFA ', '854', 1),
        (26, 'Сен-Бартелеми', 'Saint-Barteli', 'Saint-Barteli', 'BL ', 'BLM ', '652', 4),
        (30, 'Бразилия', 'Brazil', 'Brazylia', 'BR ', 'BRA ', '76 ', 6),
        (34, 'Ботсвана', 'Botswana', 'Botswana', 'BW ', 'BWA ', '72 ', 1),
        (38, 'Кокосовые острова', 'Coconut Islands', 'Wyspy kokosowe', 'CC ', 'CCK ', '166', 2),
        (40, 'Центральноафриканская Республика', 'Central African Republic', 'Republika Środkowoafrykańska', 'CF ', 'CAF ', '140', 1),
        (47, 'Сербия и Черногория', 'Serbia and Montenegro', 'Serbia i Czarnogóra', 'CS ', 'SCG ', '891', 3),
        (51, 'Остров Рождества', 'Christmas Island', 'Wyspa Bożego Narodzenia', 'CX ', 'CXR ', '162', 5),
        (55, 'Джибути', 'Djibuti', 'Djibuti', 'DJ ', 'DJI ', '262', 1),
        (58, 'Доминиканская Республика', 'Dominican Republic', 'Republika Dominikana', 'DO ', 'DOM ', '214', 4),
        (63, 'Западная Сахара', 'Western sugar', 'Sugar zachodni', 'EH ', 'ESH ', '732', 1),
        (69, 'Фолклендские острова', 'Falkland Islands', 'Wyspy Falkland', 'FK ', 'FLK ', '238', 6),
        (70, 'Федеративные Штаты Микронезии', 'Federal states of micronzia', 'Stany federalne Micronzia', 'FM ', 'FSM ', '583', 5),
        (77, 'Французская Гвиана', 'French Guvian', 'Francuski Guvian', 'GF ', 'GUF ', '254', 6),
        (81, 'Гренландия', 'Greenland', 'Grenlandia', 'GL ', 'GRL ', '304', 4),
        (85, 'Экваториальная Гвинея', 'Equatorial Guinea', 'Gwinea równikowa', 'GQ ', 'GNQ ', '226', 1),
        (87, 'Южная Георгия и Южные Сандвичевы острова', 'South George and Southern Sandwichev Islands', 'South George i Southern Sandwichev Islands', 'GS ', 'SGS ', '239', 7),
        (93, 'Остров Херд и остров Макдональд', 'Herd Island and McDonald Island', 'Herd Island i McDonald Island', 'HM ', 'HMD ', '334', 7),
        (99, 'Ирландия', 'Ireland', 'Irlandia', 'IE ', 'IRL ', '372', 3),
        (101, 'о-в Мэн', 'Froke Maine', 'Froke Maine', 'IM ', 'IMN ', '833', 3),
        (199, 'Словакия', 'Slovakia', 'Słowacja', 'SK ', 'SVK ', '703', 3),
        (200, 'Сьерра-Леоне', 'Sierra Leone', 'Sierra Leone', 'SL ', 'SLE ', '694', 1),
        (201, 'Сан-Марино', 'San Marino', 'San Marino', 'SM ', 'SMR ', '674', 3),
        (202, 'Сенегал', 'Senegal', 'Senegal', 'SN ', 'SEN ', '686', 1),
        (204, 'Суринам', 'Surinam', 'Surinam', 'SR ', 'SUR ', '740', 6),
        (205, 'Южный Судан', 'South Sudan', 'Sudan Południowy', 'SS ', 'SSD ', '728', 1),
        (207, 'Сальвадор', 'Salvador', 'Salvador', 'SV ', 'SLV ', '222', 4),
        (208, 'Сальвадор', 'Salvador', 'Salvador', 'SX ', 'SXM ', '534', 4),
        (209, 'Сирия', 'Syria', 'Syria', 'SY ', 'SYR ', '760', 2),
        (211, 'Острова Теркс и Кайкос', 'Islands Terks and Kaikos', 'Wyspy Terks i Kaikos', 'TC ', 'TCA ', '796', 4),
        (212, 'Чад', 'Chad', 'Chad', 'TD ', 'TCD ', '148', 1),
        (214, 'Того', 'Togo', 'Togo', 'TG ', 'TGO ', '768', 1),
        (215, 'Тайланд', 'Thailand', 'Tajlandia', 'TH ', 'THA ', '764', 2),
        (216, 'Таджикистан', 'Tajikistan', 'Tadżykistan', 'TJ ', 'TJK ', '762', 2),
        (217, 'Токелау', 'Tokelau', 'Tokelau', 'TK ', 'TKL ', '772', 5),
        (218, 'Восточный Тимор', 'East Timor', 'Timor wschodni', 'TL ', 'TLS ', '626', 5),
        (220, 'Тунис', 'Tunisia', 'Tunezja', 'TN ', 'TUN ', '788', 1),
        (221, 'Тонга', 'Tonga', 'Tonga', 'TO ', 'TON ', '776', 5),
        (222, 'Турция', 'Türkiye', 'Türkiye', 'TR ', 'TUR ', '792', 2),
        (224, 'Тувалу', 'Tuvalu', 'Tuvalu', 'TV ', 'TUV ', '798', 5),
        (225, 'Тайвань', 'Taiwan', 'Tajwan', 'TW ', 'TWN ', '158', 2),
        (226, 'Танзания', 'Tanzania', 'Tanzania', 'TZ ', 'TZA ', '834', 1),
        (228, 'Уганда', 'Uganda', 'Uganda', 'UG ', 'UGA ', '800', 1),
        (230, 'Уругвай', 'Uruguay', 'Urugwaj', 'UY ', 'URY ', '858', 6),
        (231, 'Узбекистан', 'Uzbekistan', 'Uzbekistan', 'UZ ', 'UZB ', '860', 2),
        (232, 'Ватикан', 'Vatican', 'Watykan', 'VA ', 'VAT ', '336', 3),
        (234, 'Венесуэла', 'Venezuela', 'Wenezuela', 'VE ', 'VEN ', '862', 6),
        (235, 'Британские Виргинские острова', 'British Virgin Islands', 'Brytyjskie Wyspy Dziewicze', 'VG ', 'VGB ', '92 ', 4),
        (237, 'Вьетнам', 'Vietnam', 'Wietnam', 'VN ', 'VNM ', '704', 2),
        (238, 'Вануату', 'Vanuatu', 'Vanuatu', 'VU ', 'VUT ', '548', 5),
        (239, 'о-ва Уоллис и Футуна', 'Front Wallis and Futuna', 'Front Wallis i Futuna', 'WF ', 'WLF ', '876', 5),
        (240, 'Самоа', 'Samoa', 'Samoa', 'WS ', 'WSM ', '882', 5),
        (241, 'Косово', 'Kosovo', 'Kosovo', 'XK ', 'XKX ', '0  ', 3),
        (242, 'Йемен', 'Yemen', 'Jemen', 'YE ', 'YEM ', '887', 2),
        (244, 'Майотта', 'Mautta', 'Mautta', 'ZA ', 'ZAF ', '710', 1),
        (245, 'Замбия', 'Zambia', 'Zambia', 'ZM ', 'ZMB ', '894', 1),
        (254, 'Чили', 'Chile', 'Chile', 'CL ', 'CHL ', '152', 6),
        (255, 'Абхазия', 'Abkhazia', 'Abchazia', 'AB ', 'ABH ', '895', 2),
        (103, 'Британская территория в Индийском океане', 'British territory in the Indian Ocean', 'Terytorium brytyjskie na Oceanie Indyjskim', 'IO ', 'IOT ', '86 ', 2),
        (111, 'Япония', 'Japan', 'Japonia', 'JP ', 'JPN ', '392', 2),
        (114, 'Камбоджа', 'Cambodia', 'Kambodża', 'KH ', 'KHM ', '116', 2),
        (117, 'Сент-Китс и Невис', 'Saint-Chits and Nevis', 'Saint-Chits i Nevis', 'KN ', 'KNA ', '659', 4),
        (118, 'Корейская Народно-Демократическая Республика', 'Korean People''s Democratic Republic', 'Koreańska Republika Demokratyczna', 'KP ', 'PRK ', '408', 2),
        (126, 'Лихтенштейн', 'Liechtenstein', 'Liechtenstein', 'LI ', 'LIE ', '438', 3),
        (131, 'Люксембург', 'Luxembourg', 'Luksemburg', 'LU ', 'LUX ', '442', 3),
        (135, 'Монако', 'Monaco', 'Monako', 'MC ', 'MCO ', '492', 3),
        (138, 'Синт-Мартен', 'Sint-Martin', 'Sint-Martin', 'MF ', 'MAF ', '663', 4),
        (141, 'Македония', 'Macedonia', 'Macedonia', 'MK ', 'MKD ', '807', 3),
        (146, 'Северные Марианские о-ва', 'Northern Mariana Islands', 'Północne Wyspy Mariany', 'MP ', 'MNP ', '580', 5),
        (149, 'Монтсеррат', 'Montserrat', 'Montserrat', 'MS ', 'MSR ', '500', 4),
        (153, 'Малави', 'Malawi', 'Malawi', 'MW ', 'MWI ', '454', 1),
        (156, 'Мозамбик', 'Mozambique', 'Mozambik', 'MZ ', 'MOZ ', '508', 1),
        (160, 'Остров Норфолк', 'Island of Norfolk', 'Wyspa Norfolk', 'NF ', 'NFK ', '574', 5),
        (163, 'Нидерланды', 'Netherlands', 'Niderlandy', 'NL ', 'NLD ', '528', 3),
        (168, 'Новая Зеландия', 'New Zealand', 'Nowa Zelandia', 'NZ ', 'NZL ', '554', 5),
        (172, 'Французская Полинезия', 'French Polynesia', 'Polinezja francuska', 'PF ', 'PYF ', '258', 5),
        (176, 'Польша', 'Poland', 'Polska', 'PL ', 'POL ', '616', 3),
        (177, 'Сен-Пьер и Микелон', 'Saint-Pierre and Michelon', 'Saint-Pierre i Michelon', 'PM ', 'SPM ', '666', 4),
        (183, 'Парагвай', 'Paraguay', 'Paragwaj', 'PY ', 'PRY ', '600', 6),
        (188, 'Россия', 'Russia', 'Rosja', 'RU ', 'RUS ', '643', 3),
        (190, 'Саудовская Аравия', 'Saudi Arabia', 'Arabia Saudyjska', 'SA ', 'SAU ', '682', 2),
        (195, 'Сингапур', 'Singapore', 'Singapur', 'SG ', 'SGP ', '702', 2),
        (198, 'Шпицберген', 'Spitsbergen', 'Spitsbergen', 'SJ ', 'SJM ', '744', 3),
        (203, 'Сомали', 'Somalia', 'Somali', 'SO ', 'SOM ', '706', 1),
        (206, 'Сан-Томе и Принсипи', 'San Tome and Principi', 'San Tome i Principi', 'ST ', 'STP ', '678', 1),
        (210, 'Эсватини', 'Esvatini', 'Esvatini', 'SZ ', 'SWZ ', '748', 1),
        (213, 'Французские Южные и Антарктические Территории', 'French southern and Antarctic territories', 'Francuskie terytoria południowe i Antarktyczne', 'TF ', 'ATF ', '260', 7),
        (219, 'Туркменистан', 'Turkmenistan', 'Turkmenia', 'TM ', 'TKM ', '795', 2),
        (223, 'Тринидад и Тобаго', 'Trinidad and Tobago', 'Trynidad i Tobago', 'TT ', 'TTO ', '780', 4),
        (227, 'Украина', 'Ukraine', 'Ukraina', 'UA ', 'UKR ', '804', 3),
        (229, 'Соединенные Штаты Америки', 'United States of America', 'Stany Zjednoczone', 'US ', 'USA ', '840', 4),
        (233, 'Сент-Винсент и Гренадины', 'Saint-Vincent and Grenadines', 'Saint-vincent i grenadyny', 'VC ', 'VCT ', '670', 4),
        (236, 'Американские Виргинские острова', 'American Virgin Islands', 'Amerykańskie Wyspy Dziewicze', 'VI ', 'VIR ', '850', 4),
        (243, 'Майотта', 'Mautta', 'Mautta', 'YT ', 'MYT ', '175', 1),
        (246, 'Зимбабве', 'Zimbabwe', 'Zimbabwe', 'ZW ', 'ZWE ', '716', 1);